@echo off
echo Setting up development environment...

echo Creating Python virtual environment...
python -m venv ..\Runtimes\Python\venv

echo Activating virtual environment...
call ..\Runtimes\Python\venv\Scripts\activate.bat

echo Updating pip package manager...
python -m pip install --upgrade pip

echo Installing runtime requirements and packages...
pip install -r ..\Runtimes\Python\requirements.txt